### ISSUE TITLE
How to troubleshoot localStorage not working with Plainpad?

### ISSUE THREAD

**Issue by virtadpt** [alextselegidis/plainpad#6] opened 2020-06-12 18:04 UTC
Platform: Samsung Galaxy Tab A, Android 9, not rooted, Firefox for Android v68.8.1
Version: Plainpad v1.0.0-beta.3, downloaded from Releases tab

Expected behavior: Log into my Plainpad instance from my tablet, notes are synched to my tablet into localStorage.  Disconnect from wireless, open Firefox, open Plainpad from bookmark, see notes synched to my tablet, do stuff with notes.

What's happening: Disconnect from wireless, open Firefox, open Plainpad from bookmark, document sidebar is empty, no notes stored locally.

Notes: Plainpad works as expected on my work laptop (OS X, Chrome 83.0.4103.61 (Official Build) (64-bit)), Android phone (Samsung SM-G965U, Android 10, Firefox for Android v68.9.0), and personal laptop (Arch Linux latest (as of 7 June 2020), Firefox v77.0.1-1) with regard to PWA!offline operation.

How can I troubleshoot what's going on?  I'd like to provide more data to help with fixing this.

**Comment by alextselegidis** [comment] 2020-07-16 10:02
Hello @virtadpt 

> What's happening: Disconnect from wireless, open Firefox, open Plainpad from bookmark, document sidebar is empty, no notes stored locally.

Did you had an open session on Firefox before? 

It seems that you logged out before going offline so that Plainpad cannot tell which user you plan on using. 

Try not logging out and then go offline and see if you can reproduce this. 

<small>
<table>
<tr>
<td><img src="https://cdn.alextselegidis.com/plainpad/logos/plainpad-online-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Plainpad Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by virtadpt** [comment] 2020-07-16 19:02
Yes, I did, and I never logged out manually.  It was, however, normal for my sessions to time out after an hour or so, forcing me to re-log in (Firefox for Linux, Firefox for Android, Chrome for OSX).

**Comment by alextselegidis** [comment] 2020-07-21 08:28
The thing is that the session is configured to work for 12 hours (hard coded value at the time being), which means that the app did not log out out due to session expiration. 

Try the following test: 

1. Log in from your phone with your account 
1. Turn on the flight mode 
1. You will still be able to use the app in offline mode 
1. Turn off the flight mode 
1. The app goes online again and your changes actually sync with the server

<small>
<table>
<tr>
<td><img src="https://cdn.alextselegidis.com/plainpad/logos/plainpad-online-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Plainpad Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment] 2020-09-15 08:09
@virtadpt This is related with #12 

I already fixed that problem, so I'm closing this ticket too. 

<small>
<table>
<tr>
<td><img src="https://cdn.alextselegidis.com/plainpad/logos/plainpad-online-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Plainpad Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Closed as completed by alextselegidis** 2020-09-15 08:09 UTC
