### ISSUE TITLE
How can we be sure that PWA functionality is actually working?

### ISSUE THREAD

**Issue by virtadpt** [alextselegidis/plainpad#12] opened 2020-07-06 20:54 UTC
I've noticed when trying to use Plainpad as a PWA (i.e., as an offline notebook that re-synchs when connectivity is restored), it only seems to work some of the time.  Sometimes my notes are available for 30 minutes to an hour, sometimes they're just not available offline.  I've done some experiments to see if it's due to the local browser not finishing the job of caching before going offline but there didn't seem to be a correlation between amount of time spent waiting for all of the device's network traffic to stop (or even waiting for it to stop), the amount of time spent waiting after the network traffic stopped, and when the network interface was downed to test local data caching.

Platforms:
Samsung Galaxy SM-G965U, Android v10, Firefox for Android v68.10.0
Samsung Galaxy Tab A (8"), Android v9, Firefox for Android v68.10.0
64-bit Arch Linux (latest), Firefox v77.0.1 (OS package)

Or, to put it another way, what are the parameters (or what is the combination of settings) necessary to ensure that Plainpad is actually usable as a PWA?

**Comment by alextselegidis** [comment] 2020-07-15 21:50
Hello @virtadpt 

Plainpad syncs notes in two different ways with the server. 

1. Changes made in the PWA get delegated to the server. 

When offline those changes will be cached and then delegated whenever there's an internet connection again. 

2. Changes from the server are being pulled and update the local database.

When offline changes from the server will not be pulled and you will only work with your local copy of the data. 

Once the device is connected to the internet again, Plainpad will compare the timestamp of the changes and will keep the one that is more recent and will discard the others. 

That is a very straightforward sync scenario that could be improved in the future but seems to work well enough for now. 

Do you have reproduction steps for a use cases that break the syncing algorithm? 

<small>
<table>
<tr>
<td><img src="https://cdn.alextselegidis.com/plainpad/logos/plainpad-online-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Plainpad Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by virtadpt** [comment] 2020-07-16 19:22
Bookmark the Plainpad install for easy access.

Log into Plainpad with Firefox for Linux or Android (Private Mode doesn't seem to make a difference).

Watch for network traffic to and from the server Plainpad's running on to stop.

Create a new or edit an existing page.

Watch for network traffic to and from the server to ensure that the traffic has finished synching.

Close the Plainpad tab.

Disconnect from the network.

Open a new Plainpad tab from the bookmark.  About 4 times out of 5 you'll still be logged in.  About one time out of five, all of the notes I created in Plainpad wil be listed down the left-hand side of the page and accessible.  The rest of the time they're not.

**Comment by alextselegidis** [comment] 2020-07-21 08:30
I will have to try this and see if I can reproduce. 

<small>
<table>
<tr>
<td><img src="https://cdn.alextselegidis.com/plainpad/logos/plainpad-online-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Plainpad Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment] 2020-09-15 07:42
@virtadpt It's been a while but other things kept me from getting back here. So it is true that there is an underlying issue, only when you start the offline. And the problem is that the app will load display the notes in the list even though they are locally cached for offline use. That does not happen when you for example start the app while being online and then go offline, as in this case the app will continue working normally. If you are offline the app will not check for credentials so that you can continue working on it normally. When you go online though you will need to login again. 

I will fix the original issue which is opening the app while being offline and it will then work just fine. A new beta will be released soon.

<small>
<table>
<tr>
<td><img src="https://cdn.alextselegidis.com/plainpad/logos/plainpad-online-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Plainpad Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Closed as completed by alextselegidis** 2020-09-15 07:42 UTC
Labels: question

**Comment by alextselegidis** [comment] 2020-09-25 10:42
Hello @virtadpt 

There's a new Plainpad version that also addresses this problem. 

This is the final pre-release before the final v1.0.0 release. 

Hello Clemens,

I hope this finds you well. 

It's been a while since we last talked, there was some vacation time in between and concentration on other projects, but there is a new Plainpad version. 

This will be the last pre-release before the final v1.0.0 and features an important offline PWA fix (when you start the app in offline mode it used to not display notes on the list until you search).

I also upgrade the framework behind the API which now uses Laravel 8. For this update you will need to make sure your server is running PHP 7.3+ 

Here's how to update:

* Ensure you are running PHP 7.3+ 
* Ensure the entire Plainpad directory is writable 777
* Go to the settings page and click the update button 
* An error will be displayed due to the laravel upgrade, that's ok
* Finalize the upgrade by running "php artisan refresh" on your console. 

If you have errors check the following places for information: 

* storage/logs/update-***.log for updater logs
* storage/logs/laravel-***.log for framework logs
* /var/log/apache2|nginx/error.log for server logs

<small>
<table>
<tr>
<td><img src="https://cdn.alextselegidis.com/plainpad/logos/plainpad-online-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Plainpad Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
